# Generated by Django 2.1.2 on 2019-10-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaifront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
