# Generated by Django 2.1.2 on 2019-11-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('icon', models.ImageField(blank=True, max_length=200, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='用户注册时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='用户更新时间')),
                ('token', models.CharField(max_length=256, verbose_name='Token')),
            ],
        ),
    ]
