# Generated by Django 2.1.2 on 2019-11-14 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='avaimg',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Personalstatement',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='个人说明'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='autograph',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='签名'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='company',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='occupation',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='职业'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phonenumber',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='照片'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
    ]
