# Generated by Django 2.1.2 on 2019-11-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0003_auto_20191114_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号'),
        ),
    ]
