# Generated by Django 2.1.2 on 2019-11-15 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0004_auto_20191114_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='Personalstatement',
            new_name='personalstatement',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile', to='eva.UserProfile'),
        ),
    ]
