# Generated by Django 2.1.2 on 2019-11-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0005_auto_20191115_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(max_length=20, unique=True, verbose_name='昵称'),
        ),
    ]
