# Generated by Django 2.1.2 on 2019-11-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0006_auto_20191123_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(max_length=20, verbose_name='昵称'),
        ),
    ]
