# Generated by Django 2.1.2 on 2019-11-27 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0007_auto_20191124_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalauthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('idnumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证号')),
                ('idfrontphoto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='身份证正面照')),
                ('idbackphoto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='身份证背面照')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='照片1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='照片2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='照片3')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='照片4')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='', verbose_name='照片5')),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='photo',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='headportrait',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nikename', to='eva.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=64, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='personalauthentication',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='eva.UserProfile'),
        ),
    ]
