# Generated by Django 2.1.2 on 2019-12-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0008_auto_20191127_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalauthentication',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='认证状态'),
        ),
    ]
