# Generated by Django 2.1.2 on 2019-12-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0009_personalauthentication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalauthentication',
            name='status',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='认证状态'),
        ),
    ]
