# Generated by Django 2.1.2 on 2019-12-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva', '0010_auto_20191209_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='邮箱'),
        ),
    ]
